### PR TITLE
chore: extracted appwrite URL to env, updated gitignore with catch-al…

### PR DESCRIPTION
**Pull request by ivanskodje**
This is my offering to you, whether or not you wish to accept is up to you :smile_cat: 

I would not want to expose my own api url, and had to manually find envs to set.

chore: extracted appwrite URL to env, updated gitignore with catch-all boilerplate, and added .env.example to make it easier to identify which .envs to set

### CODE REVIEW

**Comment by t4zzlerdeveloper** [comment]
Thank you for your contribution! 🙌 I appreciate the thoughtful approach of moving the Appwrite URL to an environment variable and the updates to .gitignore and .env.example. This makes the configuration much cleaner and improves the setup process for future contributors.

Regarding the API URL, I totally understand your concern about exposing it. Using environment variables is definitely the right call for security and flexibility. 👍

I'll review the changes in detail and get back to you soon. If everything looks good, I'm happy to merge!

Thanks again! 😸

**Review by t4zzlerdeveloper — APPROVED** [review]
Looks great! 🎉 Thanks for taking the time to extract the Appwrite URL to an environment variable and update the .gitignore with a catch-all. Including the .env.example is a nice touch that will definitely make setup easier for others.

Everything looks good to me—merging this now! 🚀

**Comment by ivanskodje** [comment]
@t4zzlerdeveloper 

I noticed we're using environment variables in other parts of the functions sub-projects. Are we planning to use the same root `.env` file for all of them?

For example, in `functions/export-pdf/src/main.py`, we have this code:

```py
    client = (
        Client()
        .set_endpoint("https://cloud.appwrite.io/v1")
        .set_project(os.environ["APPWRITE_FUNCTION_PROJECT_ID"])
        .set_key(os.environ["APPWRITE_API_KEY"])
    )
```

Will there be a separate `.env` in `/export-pdf`, or will everything use the root `.env` from the Rubium project?

Besides that, I saw you renamed `APPWRITE_URL`, but `import.meta.env.APPWRITE_URL` wasn’t updated to reflect the change to `VITE_APPWRITE_URL`.

**Comment by t4zzlerdeveloper** [comment]
@ivanskodje

First of all, thank you for bringing your expertise and insights to Rubium! 🙌

You raised an excellent point that definitely needs attention. Both the /export-pdf and /share-notes function endpoints are exposed, and since they are deployed on Appwrite, it would be helpful to dive into the [Appwrite Documentation on Function's Environment Variables](https://appwrite.io/docs/products/functions/develop#environment-variables). Specifically, the APPWRITE_FUNCTION_API_ENDPOINT might be useful for addressing this. 🛠️

For local development, I recommend [setting up Appwrite locally](https://appwrite.io/docs/products/functions/develop-locally) to streamline future contributions. Your suggestion to separate the .env file for each function is a great idea! This would ensure consistency and make managing environment variables much easier. 👍

Thanks again for your valuable input! 😊

**Pull request merged**
